### ISSUE TITLE
Grammar problems

### ISSUE THREAD

**Issue by shanasok** [shadowKnight509/FirstWebsite#2]
1. About Me page needs to have a capital L for the title and leave a space before the bracket.
2. Game page title is 'text_game'.  Perhaps change it to 'Games'.
3. Home page title is 'page'. Perhaps change it to 'Home' or something else. 
4. Joke page title should have capital 'J'.
5. About me page title should have capital 'A'.
6. Contact me page title should have capital 'C'.

**Comment by shadowKnight509** [comment]
hi
